### ISSUE TITLE
Chromesthesia should be made available in the Microsoft Store

### ISSUE THREAD

**Issue by StrangePeanut** [wader/chromesthesia#3]
The number of Edge users is growing rapidly. I would love to see this extension made available in the Microsoft Store.

**Comment by wader** [comment]
Oh sorry for the delay, didn't get any notification about the issue. Edge is suppose to be chrome extension API compatible? if so could you try install it manually somehow and see how it works? guess i have get some kind of windows environment to test it myself

**Comment by StrangePeanut** [comment]
@wader Hi mate. No worries. I’ve been using the extension without issues since early Insider builds of Edge, so it should be fully compatible.

**Comment by wader** [comment]
![Screenshot 2020-06-16 at 11 33 27](https://user-images.githubusercontent.com/185566/84758057-3f154c80-afc5-11ea-9c8c-55ffd203cfda.png)

**Comment by wader** [comment]
Was some issue with privacy policy but now it got accepted!

Could you try it? https://microsoftedge.microsoft.com/addons/detail/chromesthesia/jbolklncikkponmchgncibegnlcpkdph

**Comment by StrangePeanut** [comment]
@wader Installed with no issues!

**Comment by wader** [comment]
@StrangePeanut Thanks for testing! hope you like the software!
