### ISSUE TITLE
Result dialogue no longer appears correctly on Chromium browsers

### ISSUE THREAD

**Issue by StrangePeanut** [wader/chromesthesia#4]
![ResultDialogue](https://github.com/wader/chromesthesia/assets/56807288/176f5648-b6c7-4ad3-92a2-92945ec122d3)

**Comment by wader** [comment]
Hey, sorry didn't see this issue until now. I suspect that i fixed this in https://github.com/wader/chromesthesia/commit/0ba41743b18e8397d10b75f83b1da3850b6db19a but i haven't updated the extension in chome web store yet

**Comment by StrangePeanut** [comment]
I can confirm that it addresses the issue 👍

**Comment by StrangePeanut** [comment]
@wader I can confirm that it addresses the issue 👍

**Comment by wader** [comment]
👍 i'll see if i can get an update into web store also. I fear that the google will soon require (maybe already?) v3 manifest on updates which i think will require some rewrite to make this extension still work.

**Comment by wader** [comment]
New version in web store is now in review

**Comment by StrangePeanut** [comment]
@wader cheers! Looks like they plan on disabling V2 in Stable from July 2024 at the earliest, https://developer.chrome.com/blog/resuming-the-transition-to-mv3/#the_phase-out_timeline

**Comment by wader** [comment]
Ok! not sure how much motivation i have to look into atm. Let me know if you're up for it, have some vague memory that capture has to be done from a service worker etc now

**Comment by StrangePeanut** [comment]
@wader no problem. It is not my area of expertise but it looks doable at first glance. Might give it a crack at some point.

**Comment by wader** [comment]
👍  but no stress!
